# theme: jekyll-theme-minimal
# title: Welcome to the xhacker's homepage.
# subtitle: Whatyou looking for ?
# tags: [personal, public]
# thumbnail-img: "images/photo.png"
# description: Feel free to ideate and think about thinking.

# Site wide configuration

title: Website of Ghanendra Singh
#theme: jekyll-theme-minimal
locale: en_US
logo: "images/photo.png"
# filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Te
  avatar: bio-photo.jpg
  bio: "This is a sample Jekyll academic website."
  email: laderast@ohsu.edu
  # Do not include the @ symbol in your Twitter username
  twitter: laderast
  linkedin: #username
  github: laderast
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
