theme: jekyll-theme-minimal
title: Ghanendra Singh
tags: [personal, public]
thumbnail-img: "images/photo.png"
description: I think about thinking. Mind is curious to finding patterns and connect the dots. Masters student in Computational Biology. Bachelors in Electronics and Communication.
# Site wide configuration

#title: Website of Ghanendra Singh
#theme: jekyll-theme-minimal
#locale: en_US
logo: "images/photo.png"

# # filename of a logo image that has been placed into your images directory

# # Enter the following platform usernames if you would like for them to appear on your site.
# owner:
#   name: Ghanendra
#   avatar: bio-photo.jpg
#   bio: "This is a sample Jekyll academic website."
#   email: 22ghanendra@gmail.com
#   # Do not include the @ symbol in your Twitter username
#   twitter: 22ghanendra
#   linkedin: #username
#   github: Ghanendra19213
#   google:
#     scholar: #id
