theme: jekyll-theme-minimal
title: Welcome to the xhacker's homepage.
subtitle: Whatyou looking for ?
tags: [personal, public]
thumbnail-img: "https://github.com/Ghanendra19213/Hi/blob/master/gyani.jpg"
description: Feel free to ideate and think about thinking.
