theme: jekyll-theme-minimal
title: Ghanendra Singh
tags: [personal, public]
thumbnail-img: "images/photo.png"
description: I think about thinking. Finding patterns to understand life. One day laws of biology will get discovered.

# Site wide configuration

#title: Website of Ghanendra Singh
#theme: jekyll-theme-minimal
#locale: en_US
logo: "images/photo.png"

# # filename of a logo image that has been placed into your images directory

# # Enter the following platform usernames if you would like for them to appear on your site.
owner: Gyani
  name: Ghanendra
  avatar: bio-photo.jpg
  bio: "This is a sample Jekyll academic website."
  email: 22ghanendra@gmail.com
  # Do not include the @ symbol in your Twitter username
  twitter: 22ghanendra
  linkedin: #username
  github: Ghanendra19213
  google:
    scholar: #id
