theme: jekyll-theme-minimal
title: Welcome to the xhacker's homepage.
subtitle: Whatyou looking for ?
tags: [personal, public]
thumbnail-img: "images/photo.png"
description: Feel free to ideate and think about thinking.
